version: "3.8"

services:
  db:
    image: fitsnitch-db
    container_name: db
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fitsnitch
    ports:
      - 5432:5432
